OPENAI_API_KEY="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"
GROQ_API_KEY="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"
GOOGLE_API_KEY="AIzaSyDt8PL9xxEW0SK1ZC-gU_XIouPWXiRSwKc"
